import React from 'react';
import Head from 'next/head';

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + '-Amazona' : ''}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header> header </header>
        <main>{children}</main>
        <footer> Footer</footer>
      </div>
    </>
  );
}
